### ISSUE TITLE
Where in Hiren's Boot CD is this?

### ISSUE THREAD

**Issue by seanspotatobusiness** [kevinoid/remove-nonpresent-devices#11]
I think this script was included in the final version of Hiren's Boot CD. Does anyone know what menu options to follow to get to it? Thanks.

**Comment by kevinoid** [comment]
If so, nobody mentioned it to me.  The script modifies the registry of the running copy of Windows to remove devices which are no longer present.  It seems unlikely that it would be useful in a boot CD environment without a lot of modification (or a full rewrite).  Is it possible you are thinking of another similarly named tool?

**Comment by seanspotatobusiness** [comment]
I'm not sure. On this page: http://www.hirensbootcd.org/download/ it says one of the features added to version 15.2 of the boot disk is: _"Remove Non Present Drivers: Automatically remove all non-present/disconnected devices from a Windows and can often be useful to prevent misbehaving/unnecessary drivers from being loaded, cleanup drivers when you replaced motherboard or used backup image of different hardware."_
and the way that's written is quite similar to the description of your script. The boot CD supposedly includes some mini live version of Windows XP so maybe it runs from there but I've really no idea how that would work; I've only run it once and it wasn't responding to my keyboard so I didn't get anywhere.

**Comment by kevinoid** [comment]
Interesting.  That does sound like the same thing this script does.  I'll take a closer look.

**Comment by kevinoid** [comment]
Turns out it is this script after all.  Neat!

The script is named `RemoveDevices.js` inside `HBCD/Programs/Files/Tools.7z` on the CD.  There is a launcher to run it at `HBCD/Programs/RemoveNonPresentDrivers.cmd` which also prints the following warning:

    This program does not work from MiniXP
    You can run it from your installed Windows XP/Vista/7

So it appears that the authors intend for you to run `HBCD/Programs/RemoveNonPresentDrivers.cmd` from the CD while booted into your Windows installation.  If you wanted to pass extra options to the script, you could extract `RemoveDevices.js` and `devcon.exe` from `HBCD/Programs/Files/Tools.7z` then run `RemoveDevices.js` directly.

**Comment by kevinoid** [comment]
I hope that answered your question.  If not, feel free to reopen this issue.
